export const GET_APPLICATIONS_REQUEST = 'GET_APPLICATIONS_REQUEST'
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS'
export const GET_APPLICATIONS_FAIL    = 'GET_APPLICATIONS_FAIL'

export const CREATE_APPLICATION_REQUEST = 'CREATE_APPLICATION_REQUEST'
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS'
export const CREATE_APPLICATION_FAIL    = 'CREATE_APPLICATION_FAIL'

export const GET_APPLICATION_CREATOR_REQUEST = 'GET_APPLICATION_CREATOR_REQUEST'
export const GET_APPLICATION_CREATOR_SUCCESS = 'GET_APPLICATION_CREATOR_SUCCESS'
export const GET_APPLICATION_CREATOR_FAIL    = 'GET_APPLICATION_CREATOR_FAIL'

export const GET_APPLICATION_INCUBATOR_REQUEST = 'GET_APPLICATION_INCUBATOR_REQUEST'
export const GET_APPLICATION_INCUBATOR_SUCCESS = 'GET_APPLICATION_INCUBATOR_SUCCESS'
export const GET_APPLICATION_INCUBATOR_FAIL    = 'GET_APPLICATION_INCUBATOR_FAIL'

