export const GET_INCUBATORS_REQUEST = 'GET_INCUBATORS_REQUEST'
export const GET_INCUBATORS_SUCCESS = 'GET_INCUBATORS_SUCCESS'
export const GET_INCUBATORS_FAIL    = 'GET_INCUBATORS_FAIL'

export const CREATE_INCUBATOR_REQUEST = 'CREATE_INCUBATOR_REQUEST'
export const CREATE_INCUBATOR_SUCCESS = 'CREATE_INCUBATOR_SUCCESS'
export const CREATE_INCUBATOR_FAIL    = 'CREATE_INCUBATOR_FAIL'
