export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL    = 'GET_POSTS_FAIL'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL    = 'CREATE_POST_FAIL'


export const POST_UPVOTE_REQUEST = 'POST_UPVOTE_REQUEST'
export const POST_UPVOTE_SUCCESS = 'POST_UPVOTE_SUCCESS'
export const POST_UPVOTE_FAIL    = 'POST_UPVOTE_FAIL'


export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST'
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS'
export const GET_POST_BY_ID_FAIL    = 'GET_POST_BY_ID_FAIL'
