export const GET_REPLIES_REQUEST = 'GET_REPLIES_REQUEST'
export const GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESS'
export const GET_REPLIES_FAIL    = 'GET_REPLIES_FAIL'

export const CREATE_REPLY_REQUEST = 'CREATE_REPLY_REQUEST'
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS'
export const CREATE_REPLY_FAIL    = 'CREATE_REPLY_FAIL'

export const REPLY_UPVOTE_REQUEST = 'REPLY_UPVOTE_REQUEST'
export const REPLY_UPVOTE_SUCCESS = 'REPLY_UPVOTE_SUCCESS'
export const REPLY_UPVOTE_FAIL    = 'REPLY_UPVOTE_FAIL'
